// SPDX-FileCopyrightText: 2024 Sveriges Television AB
//
// SPDX-License-Identifier: MIT

const { spawn } = require('child_process')
const { WebSocketServer } = require('ws')
const http = require('http')

const Logger = require('../../../lib/Logger')
const logger = new Logger({ name: 'CasparNetworkPlugin' })

/**
 * Manages WebRTC proxy processes for SRT streams
 * Provides low-latency real-time preview using WebRTC
 */
class WebRTCProxy {
  constructor () {
    /** @type {Map<string, {process: any, ws: any, srtUrl: string, port: number}>} */
    this.activeProxies = new Map()
    this.wss = null
    this.server = null
    this.port = 0 // Will be set when server starts
  }

  /**
   * Start WebSocket signaling server for WebRTC
   */
  startSignalingServer (port = 0) {
    if (this.wss) {
      return this.port
    }

    this.server = http.createServer()
    this.wss = new WebSocketServer({ server: this.server })

    this.server.listen(port, '127.0.0.1', () => {
      const address = this.server.address()
      this.port = address.port
      logger.info('WebRTC signaling server started', { port: this.port })
    })

    this.wss.on('connection', (ws, req) => {
      const url = new URL(req.url, 'http://localhost')
      const streamId = url.searchParams.get('streamId')

      if (!streamId) {
        logger.warn('WebSocket connection without streamId')
        ws.close()
        return
      }

      logger.debug('WebRTC client connected', { streamId })

      // Store WebSocket connection
      const proxy = this.activeProxies.get(streamId)
      if (proxy) {
        proxy.ws = ws
      }

      ws.on('message', async (message) => {
        try {
          const data = JSON.parse(message)
          await this.handleSignalingMessage(streamId, data)
        } catch (err) {
          logger.error('Error handling signaling message', { streamId, error: err.message })
        }
      })

      ws.on('close', () => {
        logger.debug('WebRTC client disconnected', { streamId })
        const proxy = this.activeProxies.get(streamId)
        if (proxy && proxy.ws === ws) {
          proxy.ws = null
        }
      })

      ws.on('error', (err) => {
        logger.error('WebSocket error', { streamId, error: err.message })
      })
    })

    return this.port
  }

  /**
   * Handle WebRTC signaling messages
   */
  async handleSignalingMessage (streamId, data) {
    const proxy = this.activeProxies.get(streamId)
    if (!proxy || !proxy.ws) {
      logger.warn('Signaling message for unknown stream or no WebSocket', { streamId })
      return
    }

    switch (data.type) {
      case 'offer':
        // Client sent an offer, we need to create an answer based on the SDP file
        logger.debug('Received WebRTC offer', { streamId })

        try {
          // Read SDP file generated by FFmpeg
          const fs = require('fs')
          if (fs.existsSync(proxy.sdpPath)) {
            const sdpContent = fs.readFileSync(proxy.sdpPath, 'utf8')

            // Create answer SDP from the RTP SDP
            // This is a simplified approach - in production, you'd want proper SDP parsing
            const answer = {
              type: 'answer',
              sdp: sdpContent.replace(/m=video.*/, `m=video ${proxy.port} RTP/SAVPF 96\r\na=rtpmap:96 VP8/90000`).replace(/a=recvonly/g, 'a=sendonly')
            }

            proxy.ws.send(JSON.stringify({
              type: 'answer',
              answer: answer
            }))
          } else {
            logger.warn('SDP file not found, sending simple answer', { streamId, sdpPath: proxy.sdpPath })
            // Send a basic answer
            const answer = {
              type: 'answer',
              sdp: `v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\ns=FFmpeg\r\nt=0 0\r\nm=video ${proxy.port} RTP/SAVPF 96\r\na=rtpmap:96 VP8/90000\r\na=sendonly\r\n`
            }
            proxy.ws.send(JSON.stringify({
              type: 'answer',
              answer: answer
            }))
          }
        } catch (err) {
          logger.error('Error handling offer', { streamId, error: err.message })
        }
        break
      case 'ice-candidate':
        // Store ICE candidate for later use (if needed)
        logger.debug('Received ICE candidate', { streamId })
        // In a full implementation, we'd forward this to FFmpeg or handle it
        break
      default:
        logger.warn('Unknown signaling message type', { streamId, type: data.type })
    }
  }

  /**
   * Start WebRTC proxy for a stream
   * @param {string} streamId - Stream ID
   * @param {string} srtUrl - SRT URL to proxy
   * @param {Object} options - Proxy options
   * @returns {Promise<string>} WebRTC signaling URL
   */
  async startProxy (streamId, srtUrl, options = {}) {
    // Check if proxy already exists
    if (this.activeProxies.has(streamId)) {
      return `ws://127.0.0.1:${this.port}?streamId=${streamId}`
    }

    // Ensure signaling server is running
    if (!this.wss) {
      this.startSignalingServer()
      // Wait a bit for server to start
      await new Promise(resolve => setTimeout(resolve, 100))
    }

    // Generate a unique port for RTP (WebRTC uses RTP internally)
    const portHash = streamId.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0)
    const rtpPort = 50000 + (portHash % 1000)

    // Use RTP output - more reliable and widely supported
    // We'll handle WebRTC signaling separately
    return this.startRTPProxy(streamId, srtUrl, {}, rtpPort)
  }

  /**
   * Start RTP proxy and handle WebRTC signaling
   * FFmpeg outputs to RTP, and we handle WebRTC signaling via WebSocket
   */
  async startRTPProxy (streamId, srtUrl, options, rtpPort) {
    const {
      videoCodec = 'libvpx-vp8',
      audioCodec = 'libopus',
      videoBitrate = '2000k',
      audioBitrate = '128k'
    } = options

    // Use RTP output with SDP file for WebRTC
    // FFmpeg will generate an SDP file that describes the RTP stream
    const sdpPath = require('path').join(require('os').tmpdir(), `bridge-caspar-network-webrtc-${streamId}.sdp`)
    const ffmpegArgs = [
      '-fflags', '+genpts',
      '-flags', '+low_delay',
      '-strict', 'experimental',
      '-i', srtUrl,
      '-pix_fmt', 'yuv420p',
      '-c:v', videoCodec,
      '-deadline', 'realtime',
      '-cpu-used', '8',
      '-b:v', videoBitrate,
      '-maxrate', videoBitrate,
      '-bufsize', `${parseInt(videoBitrate) * 2}k`,
      '-g', '30',
      '-c:a', audioCodec,
      '-b:a', audioBitrate,
      '-f', 'rtp',
      '-sdp_file', sdpPath,
      `rtp://127.0.0.1:${rtpPort}`
    ]

    logger.debug('Starting FFmpeg RTP proxy for WebRTC', { streamId, rtpPort, sdpPath })

    const ffmpegProcess = spawn('ffmpeg', ffmpegArgs)

    ffmpegProcess.stderr.on('data', (data) => {
      const output = data.toString()
      if (output.includes('error') || output.includes('Error')) {
        logger.warn('FFmpeg RTP error', { streamId, output: output.substring(0, 200) })
      }
    })

    ffmpegProcess.on('error', (err) => {
      logger.error('FFmpeg RTP process error', { streamId, error: err.message })
      this.stopProxy(streamId)
    })

    // Store proxy info
    this.activeProxies.set(streamId, {
      process: ffmpegProcess,
      ws: null,
      srtUrl,
      port: rtpPort,
      sdpPath,
      useWebRTC: false
    })

    const signalingUrl = `ws://127.0.0.1:${this.port}?streamId=${streamId}`
    logger.info('RTP proxy started for WebRTC', { streamId, signalingUrl, rtpPort, sdpPath })
    return signalingUrl
  }

  /**
   * Stop WebRTC proxy for a stream
   * @param {string} streamId - Stream ID
   */
  stopProxy (streamId) {
    const proxy = this.activeProxies.get(streamId)
    if (!proxy) {
      return
    }

    logger.debug('Stopping WebRTC proxy', streamId)

    // Close WebSocket connection
    if (proxy.ws) {
      try {
        proxy.ws.close()
      } catch (err) {
        logger.warn('Error closing WebSocket', { streamId, error: err.message })
      }
    }

    // Kill FFmpeg process
    if (proxy.process && !proxy.process.killed) {
      proxy.process.kill('SIGTERM')
    }

    this.activeProxies.delete(streamId)
    logger.debug('WebRTC proxy stopped', streamId)
  }

  /**
   * Get proxy info for a stream
   * @param {string} streamId - Stream ID
   * @returns {Object|null} Proxy info or null
   */
  getProxy (streamId) {
    return this.activeProxies.get(streamId) || null
  }

  /**
   * Check if proxy is active for a stream
   * @param {string} streamId - Stream ID
   * @returns {boolean}
   */
  isActive (streamId) {
    return this.activeProxies.has(streamId)
  }

  /**
   * Stop all active proxies
   */
  stopAll () {
    for (const streamId of this.activeProxies.keys()) {
      this.stopProxy(streamId)
    }
  }

  /**
   * Stop signaling server
   */
  stopSignalingServer () {
    if (this.wss) {
      this.wss.close()
      this.wss = null
    }
    if (this.server) {
      this.server.close()
      this.server = null
    }
    this.port = 0
    logger.debug('WebRTC signaling server stopped')
  }
}

module.exports = WebRTCProxy
